name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: codota/toolchain@00a8bf2bdcfe93aefd70422d3dec07337959d3a4
        with:
          profile: minimal
      - name: Install protobuf
        run: sudo apt-get install -y protobuf-compiler
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --release --all-targets --all-features -- -D warnings
        continue-on-error: false
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Test && Generate code coverage
        run: cargo tarpaulin --all-features --workspace --locked  --ignore-tests -o Xml -o lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
      - name: Build pallets
        run: cargo build --release --locked

